name: Build & Release

on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'
      - 'v[0-9]*.[0-9]*.[0-9]*-alpha.[0-9]*'
      - 'v[0-9]*.[0-9]*.[0-9]*-beta.[0-9]*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  build-android:
    needs: setup
    uses: ./.github/workflows/build-android.yml
    with:
      version: ${{ needs.setup.outputs.version }}
      flutter_version: ${{ needs.setup.outputs.flutter_version }}
    secrets:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

  build-ios:
    needs: setup
    uses: ./.github/workflows/build-ios.yml
    with:
      version: ${{ needs.setup.outputs.version }}
      flutter_version: ${{ needs.setup.outputs.flutter_version }}

  release:
    needs: [setup, build-android, build-ios]
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.setup.outputs.tag }}
      version: ${{ needs.setup.outputs.version }}
      is_alpha: ${{ needs.setup.outputs.is_alpha }}
      is_beta: ${{ needs.setup.outputs.is_beta }}
      release_notes: ${{ needs.setup.outputs.release_notes }}
    secrets:
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
      MASTODON_INSTANCE: ${{ secrets.MASTODON_INSTANCE }}
